config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :articles
  root to: 'pages#index'
  
  
  get 'pages/index'

  get 'pages/contact'

  get 'pages/about'
  
  get 'pages/testing'
  
  post 'pages/result'
  
  post 'pages/testresult'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Tone bank was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Tone bank was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Tone bank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
  	<%= stylesheet_link_tag "Piano-Keyboard" %>
		<%= javascript_include_tag "Piano-Keyboard", defer: true %>
		<%= javascript_include_tag "demo", defer: true %>

<%= form_for(@article) do |f| %>
  <%#= f.error_notification %>

  <div class="form-inputs">
     <p><%= f.label "Name:" %>
   <%= f.text_field :title, label: "Name" %></p>
   <br>
    <p><%= f.label "Pitches:" %>
    <%= f.text_area :body, label: "Pitches", id: "fullEvents", style: "resize:none" %></p>
    <openmusic-piano-keyboard id="full" octaves="1"></openmusic-piano-keyboard>
  </div>
  <br>
  <div class="form-actions">
  <p> <%= f.button "Next chord", :type => "button",:onclick => "nextchord()" %>
 <%= f.button "Clear", :type => "button",:onclick => "clearbank()" %></p> 
 <br>
    <%= f.button  "Create Tone Bank", :type => "button",:onclick => "banksubmit()" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div style="margin-left:20px">
<h1>Editing Tone Bank</h1>

<%= render 'form' %>

<%#= link_to 'Show', @article %> 
<%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<div style="margin-left:20px">
<p id="notice"><%= notice %></p>

<h1>Current Tone Banks</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Pitches</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tone Bank', new_article_path %>
</div>

app/views/articles/new.html.erb
<div style="margin-left:20px">
<h1>New Tone Bank</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div style="margin-left:20px">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Pitches:</strong>
  <%= @article.body %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>
</div>