config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :articles
  root to: 'pages#index'
  
  
  get 'pages/index'

  get 'pages/contact'

  get 'pages/about'
  
  get 'pages/testing'
  
  post 'pages/result'
  
  post 'pages/testresult'
  

end

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<body onload="update()">
  <% javascript_include_tag "distribbox" %>

  
    <!-- h1>Index </h1> --!>
<div style="margin-left:20px">


<%= form_for :session, url: pages_result_path, :html => { :method => 'POST' } do |f| %>


  <p><%= f.label "Tone bank:" %>
  <%= f.select(:tonebank, @articles.collect {|r| r.title }) %></p>
  <p><%= f.label "Tone bank instrument:" %>
  <%#= f.input(:tonebank) %>
  <%= f.select :tonebankinstr, options_for_select(PagesHelper::GM_PATCH_NAMES, selected: PagesHelper::GM_PATCH_NAMES[108]) %></p>
  <p><%= f.label "Number of tone bank cycles:" %>
  <%= f.number_field(:numcycles, in: 4..256, :value =>16) %></p>
    <p><%= f.label "BPM:" %>
  <%= f.number_field(:bpm, in: 1..255,:value =>120) %></p>
  
    <p><%= f.label "Beats:" %>
  <%= f.number_field(:tsnum, in: 1..20,:value =>4) %>
   <p> <%= f.label "Divisions:" %>
  <%= f.select :divs, options_for_select([3,4,5],selected:3)  %></p>
  
      <p><%= f.label "Swing:" %>
    <% (0..4).each do |i| %>
        <% if i <= 2 %>
          <%= f.label(":", id:"colon[#{i}]") if i >0 %>
          <%= f.number_field("swing[#{i}]",in: 1..7,:value =>1) %>
          
        <% else %>
          <%= f.label(":", id:"colon[#{i}]",:hidden=>true) if i >0 %>
          <%= f.number_field("swing[#{i}]",in: 1..7,:value =>1,:hidden=>true) %>
        <% end %>
    <% end %>
  </p>
  </p>
  
    <p><%= f.label "Shaker:" %>
    <% (0..99).each do |i| %>
      <% if i <= 11 %>
        <%= f.check_box("shaker[#{i}]",:checked => (i%3==0?true:false)) %>
        <%= f.label("\u00a0", id:"space3[#{i}]") if i % 3 == 2 %>          
      <% else %>
        <%= f.check_box("shaker[#{i}]",:checked => (i%3==0?true:false),:hidden=>true) %>
        <%= f.label("\u00a0", id:"space3[#{i}]",:hidden=>true) if i % 3 == 2 %>   
      <% end %>
      <%= f.label("\u00a0", id:"space4[#{i}]",:hidden=>true) if i % 4 == 3 %>
      <%= f.label("\u00a0", id:"space5[#{i}]",:hidden=>true) if i % 5 == 4 %>
    <% end %>
  </p>
  
    <p><%= f.label "Join repeated notes within a word:" %>
  <%= f.check_box(:repeat,:value =>false) %></p>

  <p><%= f.label "Solo instrument:" %>
  <%= f.select :instr, options_for_select(PagesHelper::GM_PATCH_NAMES, selected: PagesHelper::GM_PATCH_NAMES[73]) %></p>
  
  <b> Solo instrument range (mid C = 60):</b>
  
  <p><%= f.label "bottom:" %>
  <%= f.number_field(:bottom, in: 1..255,:value =>55) %>
  <%= f.label "top:" %>
  <%= f.number_field(:top, in: 1..255,:value =>79) %></p>
  <b>
  <p><%= f.label "First phrase length:" %>
  <%= f.number_field(:initlen, in: 1..7,:value =>3) %></p>
    <p><%= f.label "Minimum phrase rhythmic variation:" %>
  <%= f.number_field(:minrhythmvar, in: 0..20,:value =>1) %></p>
  <p><%= f.label "Maximum phrase rhythmic variation:" %>
  <%= f.number_field(:maxrhythmvar, in: 0..20,:value =>1) %></p>

  <b> Melodic movement probability distribution:</b>
  <div style="font-size:8px">



  <table frame = "box">
    <tr>
      <% (-12..12).each do |i| %>
      <%= content_tag :td, align: "center" do %>
        <% "#{i}" %>
      <% end %>
      <% end %>
    </tr>
     <tr>
      <% (0..24).each do |i| %>
        <%= content_tag :td, align: "center" do %>
          <%#= f.label "label_#{i}", id: "cycles_label_#{i}" %>
          <%= f.number_field("numvals[#{i}]", in: 0..100, id: "vals_box_#{i}", :value =>100, :onchange => "changerect(#{i})" ) %>
        <% end %>
      <% end %>
    </tr>
    <tr>
      <% (0..24).each do |i| %>
        <%= content_tag :td, align: "center", id: "distrib_#{i}" do %>
        <% end %>
      <% end %>
    </tr>
    <tr>
      <% (0..24).each do |i| %>
        <%= content_tag :td, align: "center", id: "perc_#{i}" do %>
        0
        <% end %>
      <% end %>
    </tr>


  </table>

</div>
      <p> <%= f.label "Mean:" %>
      <%= f.number_field("Binomial", in: 1..200, id: "binomial_box", :value =>40 ) %>
      <%= f.button "Update", :type => "button",:onclick => "update()" %></p> 

  <p><%= f.submit "Generate", :type => "button",:onclick => "document.forms[0].submit()" %></p> 
  
 
<% end %>




</div>

<script type="text/javascript">

$(function(){
    
    $("#session_divs").on("change", function(){
      for(i=0; i<99; i++){
        
        if (i < $("#session_divs").val() * $("#session_tsnum").val() ){
          $("#session_shaker\\["+i+"\\]").show();
          if($("#session_divs").val()=="3") {$("#space3\\["+i+"\\]").show();$("#space5\\["+i+"\\]").hide();$("#space4\\["+i+"\\]").hide()}
          if($("#session_divs").val()=="4") {$("#space3\\["+i+"\\]").hide();$("#space5\\["+i+"\\]").hide();$("#space4\\["+i+"\\]").show()}
          if($("#session_divs").val()=="5") {$("#space3\\["+i+"\\]").hide();$("#space5\\["+i+"\\]").show();$("#space4\\["+i+"\\]").hide()}
          if( i % $("#session_divs").val()==0) {
            $("#session_shaker\\["+i+"\\]").prop('checked',true);
          } else {

            $("#session_shaker\\["+i+"\\]").prop('checked',false);
          }  
        }
        else {
          $("#session_shaker\\["+i+"\\]").hide();
        }
      
      }

      for (i = 0; i < 5; i++) {
        if(i<$("#session_divs").val()){
          $("#session_swing\\["+i+"\\]").show();
          $("#colon\\["+i+"\\]").show();
        }
        else {
          $("#session_swing\\["+i+"\\]").hide();
          $("#colon\\["+i+"\\]").hide();
        }
        
      }
      
});
 $("#session_tsnum").on("change", function(){
      for(i=0; i<99; i++){
        
        if (i < $("#session_divs").val() * $("#session_tsnum").val() ){
          $("#session_shaker\\["+i+"\\]").show();
          if($("#session_divs").val()=="3") {$("#space3\\["+i+"\\]").show();$("#space5\\["+i+"\\]").hide();$("#space4\\["+i+"\\]").hide()}
          if($("#session_divs").val()=="4") {$("#space3\\["+i+"\\]").hide();$("#space5\\["+i+"\\]").hide();$("#space4\\["+i+"\\]").show()}
          if($("#session_divs").val()=="5") {$("#space3\\["+i+"\\]").hide();$("#space5\\["+i+"\\]").show();$("#space4\\["+i+"\\]").hide()}
          if( i % $("#session_divs").val()==0) {
            $("#session_shaker\\["+i+"\\]").prop('checked',true);
          } else {

            $("#session_shaker\\["+i+"\\]").prop('checked',false);
          }  
        }
        else {
          $("#session_shaker\\["+i+"\\]").hide();
        }
      
      }

      for (i = 0; i < 5; i++) {
        if(i<$("#session_divs").val()){
          $("#session_swing\\["+i+"\\]").show();
          $("#colon\\["+i+"\\]").show();
        }
        else {
          $("#session_swing\\["+i+"\\]").hide();
          $("#colon\\["+i+"\\]").hide();
        }
        
      }
      
});

});


</script>

</body>

app/views/pages/result.html.erb
<!--h1>Harmony test </h1> -->

<%# if current_user %>
    <%= image_tag "outputfile.png" %>
    <%= link_to 'Back', root_path %>
    
    

app/views/pages/testing.html.erb
<!doctype html>

<html>
  	<%= stylesheet_link_tag "Piano-Keyboard" %>
		<%= javascript_include_tag "Piano-Keyboard", defer: true %>
		<%= javascript_include_tag "demo", defer: true %>
	<head>
		<meta charset="utf8">
		<title>piano keyboard demo</title>

	</head>
	
	<body>
		<h1>piano keyboard demo</h1>
		
		<%= form_for :session, url: pages_testresult_path, :html => { :method => 'POST' } do |f| %>
		
		
		<p>
			<openmusic-piano-keyboard id="full" octaves="1"></openmusic-piano-keyboard>
			<!--span id="fullEvents"></span-->
			<%= f.text_field :body, label: "Pitches", id: "fullEvents" %>
		</p>
		<p> <%= f.button "Next chord", :type => "button",:onclick => "nextchord()" %></p>
    <p>  <%= f.button "Clear", :type => "button",:onclick => "clearbank()" %></p> 

  <p><%= f.submit "Generate", :type => "button",:onclick => "document.forms[0].submit()" %></p> 
		<% end %>
	</body>
</html>