config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :articles
  root to: 'pages#index'
  
  
  get 'pages/index'

  get 'pages/contact'

  get 'pages/about'
  
  get 'pages/testing'
  
  post 'pages/result'
  
  post 'pages/testresult'
  

end

app/views/layouts/_foot.html.erb
     <footer class="footer-distributed ">

        <div class="footer-left ">

          <h3>My<span>Volo</span></h3>

          <p class="footer-links ">
            <a href="# ">Home</a> ·
            <a href="# ">Blog</a> ·
            <a href="# ">Pricing</a> ·
            <a href="# ">About</a>
            <br>
            <a href="# ">Site Map</a> ·
            <a href="# ">Faq</a> ·
            <a href="# ">Contact</a> ·
            <!-- (phone? mail?) -->
            <a href="# ">Legal</a>
            <!-- (privacy policy, terms of use) -->
          </p>
          <p class="footer-company-name ">&copy; Member Solutions 2016</p>
          <div class="footer-icons ">
            <a href="# "><i class="fa fa-facebook"></i></a>
            <a href="# "><i class="fa fa-twitter"></i></a>
            <a href="# "><i class="fa fa-youtube"></i></a>
            <a href="# "><i class="fa fa-instagram"></i></a>
          </div>
        </div>
        <div class="footer-right">
          <p>Contact Us</p>
          <form action="#" method="post">
            <input type="text " name="email " placeholder="Email ">
            <textarea name="message " placeholder="Message "></textarea>
            <button class="send-button-text">Send</button>
          </form>
        </div>
      </footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default"> <div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display --> <div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs- example-navbar-collapse-1" aria-expanded="false">
<span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<%= link_to "Music Project", root_path, class: 'navbar-brand' %> </div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav navbar-right">
<li><%#= link_to "Contact Us", pages_contact_path %></li>
<li><%#= link_to "About Us", pages_about_path %></li>
<li><%= link_to "Add a Tone Bank", new_article_path %></li>
<li><%= link_to "Edit Tone Banks", articles_path %></li>
<% if !current_user %>
<li><%= link_to "Sign Up", new_user_registration_path %></li> 
<li><%= link_to "Sign In", new_user_session_path %></li>
<% else %>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
<ul class="dropdown-menu">
<li><a href="#">Action</a></li>
<li><a href="#">Another action</a></li>
<li><%= link_to "Edit My Profile", edit_user_registration_path %></li> <li role="separator" class="divider"></li>
Chesnowitz Interactive Ruby-on-Rails-a-Beginners-Guide www.chesnowitz.com
 <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li> </ul>
</li>
</ul>
<% end %>
</div><!-- /.navbar-collapse --> </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

<%= render 'layouts/nav' %>
<%= bootstrap_flash %>
<div class='container'>

</div>

<%= yield %>

</body>
</html>